# Generated by Django 5.0.6 on 2024-05-28 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reimbursements", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reimbursement",
            name="date",
        ),
        migrations.RemoveField(
            model_name="reimbursement",
            name="expense_type",
        ),
        migrations.RemoveField(
            model_name="reimbursement",
            name="manager_comments",
        ),
        migrations.RemoveField(
            model_name="reimbursement",
            name="receipt",
        ),
        migrations.AddField(
            model_name="reimbursement",
            name="category",
            field=models.CharField(
                choices=[
                    ("travel", "Travelling"),
                    ("relocation", "Re-location"),
                    ("tech_assets", "Tech Assets"),
                ],
                default="travel",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reimbursement",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="reimbursement",
            name="description",
            field=models.TextField(default="No description provided"),
        ),
        migrations.AddField(
            model_name="reimbursement",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="reimbursement",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="reimbursement",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
