# Generated by Django 5.0.6 on 2024-05-30 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reimbursements", "0002_remove_reimbursement_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reimbursement",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reimbursements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
