# Generated by Django 5.0.6 on 2024-05-31 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reimbursements", "0005_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("deleted", "Deleted"),
                    ("accessed", "Accessed"),
                ],
                default="accessed",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="reimbursement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="reimbursements.reimbursement",
            ),
        ),
    ]
