# Generated by Django 5.0.6 on 2024-06-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reimbursements", "0006_alter_auditlog_action_alter_auditlog_reimbursement"),
    ]

    operations = [
        migrations.AddField(
            model_name="reimbursement",
            name="manager_comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
