# Generated by Django 5.0.6 on 2024-06-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reimbursements", "0007_reimbursement_manager_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="reimbursement",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
